using UnityEngine;

/// <summary>Flat brick world used as a scratchpad for authoring setpieces with the
/// console "edit" command. Non-grass floor keeps the Abyss scatter tasks (graveyard,
/// raider camp, pond, outpost, dungeon entrance) as no-ops if this world is ever
/// regenerated by Gen.GenerateAllFor.</summary>
public class GenEdit : Gen
{
    private static int _id;
    private static int Brick => _id == 0 ? Block.ConvertID(ID.BrickBlock) : _id;

    public override Vector3Int GetSize() => new Vector3Int(15, 4, 15);
    public override Vector3Int GetSpawnPoint() => new Vector3Int(GetSize().x / 2, 1, GetSize().z / 2) * World.ChunkSize;

    protected override void GenChunk(Vector3Int currentCoordinate, Chunk currentChunk)
    {
        if (currentCoordinate.y == 0)
            for (int z = 0; z < World.ChunkSize; z++)
            for (int x = 0; x < World.ChunkSize; x++)
                currentChunk[x, 0, z] = Brick;
    }

    /// <summary>Generates only the flat terrain (no scatter/gen-post tasks) into a fresh edit world.</summary>
    public static void GenerateFlat(World world)
    {
        GenEdit gen = new GenEdit();
        for (int cx = 0; cx < world.Size.x; cx++)
            for (int cy = 0; cy < world.Size.y; cy++)
                for (int cz = 0; cz < world.Size.z; cz++)
                {
                    Vector3Int coord = new Vector3Int(cx * World.ChunkSize, cy * World.ChunkSize, cz * World.ChunkSize);
                    Chunk chunk = new Chunk();
                    world[coord] = chunk;
                    gen.GenChunk(coord, chunk);
                }
    }
}
